### ISSUE TITLE
Create tests for API on User

### ISSUE THREAD

**Issue by iesteban** [Semillas/semillas_platform#1]
A simple test using the functionalities of django rest framework: http://www.django-rest-framework.org/api-guide/testing/

Run tests with: 
`$ docker-compose -f dev.yml run python manage.py test`

More info in: https://docs.djangoproject.com/en/1.10/topics/testing/overview/

**Comment by pilamb** [comment]
I am curious if nosetest or regular UT would work:
 $ docker-compose -f dev.yml run python -m unittest --discover
