### ISSUE TITLE
Create Wallet Model

### ISSUE THREAD

**Issue by iesteban** [Semillas/semillas_platform#11]
Every user will have a wallet entity connected. The Wallet model can be taken from this one: 
https://github.com/jpanganiban/django-pursed

I think the Transaction model should have also the source wallet of the transaction.

**Comment by sergimartnez** [comment]
@iesteban do you think is better to create the Wallet model class within the User models file, or do we need to create a whole new Model for wallet (new folder with all the required files)?

**Comment by iesteban** [comment]
It should be created like is shown here:

[https://docs.djangoproject.com/en/1.10/intro/tutorial01/#creating-the-polls-app](https://docs.djangoproject.com/en/1.10/intro/tutorial01/#creating-the-polls-app)

And instead of poll wallet.

**Comment by pilamb** [comment]
@sergimartinez wallet should be modelled as a whole Django app. Separared from user , but related @iesteban points
