### ISSUE TITLE
Create Chat logic

### ISSUE THREAD

**Issue by iesteban** [Semillas/semillas_platform#23]
Due to the match of technologies to use we should get inspired by: 

https://github.com/iesteban/channel_chat

Avoiding the group chat.

Notes: Check out authentication.

**Comment by s-nt-s** [comment]
look semillas_backend/tree/xmpp
https://raw.githubusercontent.com/rroemhild/docker-ejabberd/master/examples/docker-compose/docker-compose.yml

**Comment by s-nt-s** [comment]
Resources for a xmpp approach:

- https://github.com/rroemhild/docker-ejabberd
- https://github.com/mathiasertl/django-xmpp-account
- https://github.com/fpytloun/django-xmpp
