### ISSUE TITLE
Prepare Landing 'sign-up'  and 'successfully signed-up' pages for gathering e-mails

### ISSUE THREAD

**Issue by iesteban** [Semillas/semillas_platform#32]
The goal is to encourage people to sign-up in our landing page with the promise of keeping them up to date and notify them as soon as we launch the first version of the product. 

So the sign-up should include a text like: 
"We are not live yet, but we can keep you updated of our improvements and notify you once we launch" 

And the after sign-up page should have a message like: 
"Thanks a lot for joining. We will keep you posted. Keep reading about us" And a link to 'people' tab.

**Comment by carquet** [comment]
It's been corrected and added.
I sent a pull request
