### ISSUE TITLE
Make default language English

### ISSUE THREAD

**Issue by iesteban** [Semillas/semillas_platform#4]
To every user not having the browser in English, the web is showing up in Spanish. 

So anyone from... France for example opening the web, it will be in Spanish. 

Also in order to have the strings inside the code written in English would be great to have the default language as English.

**Comment by pilamb** [comment]
isnt it this donde with settings.py? cookies maybe?
Maybe you can give some hint on how you want it ...links to documentation would be very helpful and concise

**Comment by iesteban** [comment]
Yes, is inside settings. But also requires to put all text strings in English.
